### ISSUE TITLE
Restarting the Framework Results in Framework not starting

### ISSUE THREAD

**Issue by nicgrayson** [mesosphere/hdfs#43]
```
bin/hdfs-mesos
2015-01-13 21:48:11,191:19961(0x7f13df9c9700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-01-13 21:48:11,192:19961(0x7f13df9c9700):ZOO_INFO@log_env@716: Client environment:host.name=<edited>
2015-01-13 21:48:11,192:19961(0x7f13df9c9700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-01-13 21:48:11,192:19961(0x7f13df9c9700):ZOO_INFO@log_env@724: Client environment:os.arch=3.13.0-35-generic
2015-01-13 21:48:11,192:19961(0x7f13df9c9700):ZOO_INFO@log_env@725: Client environment:os.version=#62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014
2015-01-13 21:48:11,192:19961(0x7f13df9c9700):ZOO_INFO@log_env@733: Client environment:user.name=nicgrayson
2015-01-13 21:48:11,193:19961(0x7f13df9c9700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2015-01-13 21:48:11,193:19961(0x7f13df9c9700):ZOO_INFO@log_env@753: Client environment:user.dir=/home/nicgrayson/hdfs-mesos-0.0.2
2015-01-13 21:48:11,193:19961(0x7f13df9c9700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=<edited>:2181 sessionTimeout=20000 watcher=0x7f13e2e8e6a0 sessionId=0 sessionPasswd=<null> context=0x7f13f8000bb0 flags=0
2015-01-13 21:48:11,220:19961(0x7f13dc5c7700):ZOO_INFO@check_events@1703: initiated connection to server [<edited>:2181]
2015-01-13 21:48:11,221:19961(0x7f13dc5c7700):ZOO_INFO@check_events@1750: session establishment complete on server [<edited>:2181], sessionId=0x14a0bf60f1d01d6, negotiated timeout=20000
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0113 21:48:11.610419 19983 sched.cpp:1085]
**************************************************
Scheduler driver bound to loopback interface! Cannot communicate with remote master(s). You might want to set 'LIBPROCESS_IP' environment variable to use a routable IP address.
**************************************************
2015-01-13 21:48:11,611:19961(0x7f13df1c8700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-01-13 21:48:11,612:19961(0x7f13df1c8700):ZOO_INFO@log_env@716: Client environment:host.name=<edited>
2015-01-13 21:48:11,612:19961(0x7f13df1c8700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-01-13 21:48:11,620:19961(0x7f13df1c8700):ZOO_INFO@log_env@724: Client environment:os.arch=3.13.0-35-generic
2015-01-13 21:48:11,620:19961(0x7f13df1c8700):ZOO_INFO@log_env@725: Client environment:os.version=#62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014
2015-01-13 21:48:11,620:19961(0x7f13df1c8700):ZOO_INFO@log_env@733: Client environment:user.name=nicgrayson
2015-01-13 21:48:11,620:19961(0x7f13df1c8700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2015-01-13 21:48:11,620:19961(0x7f13df1c8700):ZOO_INFO@log_env@753: Client environment:user.dir=/home/nicgrayson/hdfs-mesos-0.0.2
2015-01-13 21:48:11,620:19961(0x7f13df1c8700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=<edited>:2181 sessionTimeout=10000 watcher=0x7f13e2e8e6a0 sessionId=0 sessionPasswd=<null> context=0x7f13ec000fa0 flags=0
I0113 21:48:11.622208 19983 sched.cpp:137] Version: 0.21.1
2015-01-13 21:48:11,636:19961(0x7f13d7c89700):ZOO_INFO@check_events@1703: initiated connection to server [<edited>:2181]
2015-01-13 21:48:11,638:19961(0x7f13d7c89700):ZOO_INFO@check_events@1750: session establishment complete on server [<edited>:2181], sessionId=0x14a0bf60f1d01d7, negotiated timeout=10000
I0113 21:48:11.638434 19976 group.cpp:313] Group process (group(1)@127.0.0.1:57886) connected to ZooKeeper
I0113 21:48:11.638603 19976 group.cpp:790] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I0113 21:48:11.638711 19976 group.cpp:385] Trying to create path '/mesos' in ZooKeeper
I0113 21:48:11.641079 19976 detector.cpp:138] Detected a new leader: (id='10')
I0113 21:48:11.641466 19976 group.cpp:659] Trying to get '/mesos/info_0000000010' in ZooKeeper
I0113 21:48:11.642685 19976 detector.cpp:433] A new leading master (UPID=master@<edited>:5050) is detected
I0113 21:48:11.642915 19976 sched.cpp:234] New master detected at master@<edited>:5050
I0113 21:48:11.643306 19976 sched.cpp:242] No credentials provided. Attempting to register without authentication
I0113 21:48:11.653475 19976 sched.cpp:736] Got error 'Completed framework attempted to re-register'
I0113 21:48:11.653612 19976 sched.cpp:1320] Asked to abort the driver
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: org/apache/log4j/Level
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
	at org.eclipse.jetty.util.log.Slf4jLog.<init>(Slf4jLog.java:38)
	at org.eclipse.jetty.util.log.Slf4jLog.<init>(Slf4jLog.java:32)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:374)
	at org.eclipse.jetty.util.log.Log.initialized(Log.java:177)
	at org.eclipse.jetty.util.log.Log.getLogger(Log.java:290)
	at org.eclipse.jetty.util.log.Log.getLogger(Log.java:280)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.<clinit>(AbstractLifeCycle.java:35)
	at org.apache.mesos.hdfs.config.ConfigServer.<init>(ConfigServer.java:32)
	at org.apache.mesos.hdfs.config.ConfigServer$$FastClassByGuice$$108decf1.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
	at org.apache.mesos.hdfs.Main.main(Main.java:14)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Level
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 26 more
Jan 13, 2015 9:48:11 PM org.apache.mesos.hdfs.Scheduler error
SEVERE: Scheduler driver error: Completed framework attempted to re-register
I0113 21:48:11.832442 19976 sched.cpp:777] Aborting framework '20141218-034535-553716234-5050-2178-0108'
2015-01-13 21:48:11.871:INFO::main: Logging initialized @3102ms
2015-01-13 21:48:12.055:INFO:oejs.Server:main: jetty-9.2.z-SNAPSHOT
2015-01-13 21:48:12.305:INFO:oejs.ServerConnector:main: Started ServerConnector@1ad70640{HTTP/1.1}{0.0.0.0:8765}
2015-01-13 21:48:12.306:INFO:oejs.Server:main: Started @3686ms
```

**Comment by elingg** [comment]
Thanks, @nicgrayson. This fix is planned for our blog ready milestone. 

As a temporary workaround, please either clear the zookeeper state or create a unique framework id upon relaunch, i.e. "/hdfs-mesos/" + conf.getClusterName() + System.currentTimeinMillis() .

 ZooKeeperState zkState = new ZooKeeperState(conf.getStateZkServers(),
        conf.getStateZkTimeout(), TimeUnit.MILLISECONDS, "/hdfs-mesos/" + conf.getClusterName());

**Comment by nicgrayson** [comment]
I have this working but I'm having issues with task reconciliation on reregistration. I should have a PR in next week. The biggest thing is moving up to mesos 0.21.0.

**Comment by elingg** [comment]
To me task reconciliation is a separate issue, but adding both these two important fixes in one shot also sounds great to me. If you want to submit in two separate PR's, a solution is to restart all the tasks upon reregistration.

**Comment by nicgrayson** [comment]
This is fixed with #72

**Comment by samos123** [comment]
I'm using the following commit 13d2c07e0502250a0e41a0314f3efe86560c8f35 but still having this issue. This is the related log:
```
2015-07-31 03:41:29,995:4392(0x7f1c3315a700):ZOO_INFO@log_env@733: Client environment:user.name=ubuntu                                                        [42/1468]
2015-07-31 03:41:29,995:4392(0x7f1c3315a700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2015-07-31 03:41:29,995:4392(0x7f1c3315a700):ZOO_INFO@log_env@753: Client environment:user.dir=/root/hdfs/build/hdfs-mesos-0.1.3
2015-07-31 03:41:29,995:4392(0x7f1c3315a700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=localhost:2181 sessionTimeout=20000 watcher=0x7f1c6cc7a340
 sessionId=0 sessionPasswd=<null> context=0x7f1c14000930 flags=0
2015-07-31 03:41:29,996:4392(0x7f1c31957700):ZOO_INFO@check_events@1703: initiated connection to server [127.0.0.1:2181]
2015-07-31 03:41:30,010:4392(0x7f1c31957700):ZOO_INFO@check_events@1750: session establishment complete on server [127.0.0.1:2181], sessionId=0x944ee1dc872d0006, negot
iated timeout=20000
2015-07-31 03:41:30,057:4392(0x7f1c36160700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-07-31 03:41:30,057:4392(0x7f1c36160700):ZOO_INFO@log_env@716: Client environment:host.name=mesos-master-7e03a4d1-2b98-47bf-8d57-d6ef5d7fda3e
2015-07-31 03:41:30,057:4392(0x7f1c36160700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-07-31 03:41:30,057:4392(0x7f1c36160700):ZOO_INFO@log_env@724: Client environment:os.arch=3.13.0-57-generic
2015-07-31 03:41:30,057:4392(0x7f1c36160700):ZOO_INFO@log_env@725: Client environment:os.version=#95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015
I0731 03:41:30.057566  4422 sched.cpp:157] Version: 0.23.0
2015-07-31 03:41:30,057:4392(0x7f1c36160700):ZOO_INFO@log_env@733: Client environment:user.name=ubuntu
2015-07-31 03:41:30,058:4392(0x7f1c36160700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2015-07-31 03:41:30,058:4392(0x7f1c36160700):ZOO_INFO@log_env@753: Client environment:user.dir=/root/hdfs/build/hdfs-mesos-0.1.3
2015-07-31 03:41:30,058:4392(0x7f1c36160700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=mesos-master:2181 sessionTimeout=10000 watcher=0x7f1c6cc7a
340 sessionId=0 sessionPasswd=<null> context=0x7f1c240015b0 flags=0
2015-07-31 03:41:30,063:4392(0x7f1c2bfff700):ZOO_INFO@check_events@1703: initiated connection to server [192.168.111.54:2181]
03:41:30.065 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @864ms
2015-07-31 03:41:30,081:4392(0x7f1c2bfff700):ZOO_INFO@check_events@1750: session establishment complete on server [192.168.111.54:2181], sessionId=0x924ee1dc84a80005, 
negotiated timeout=10000
I0731 03:41:30.081396  4416 group.cpp:313] Group process (group(1)@192.168.111.56:54093) connected to ZooKeeper
I0731 03:41:30.081466  4416 group.cpp:787] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I0731 03:41:30.081490  4416 group.cpp:385] Trying to create path '/mesos' in ZooKeeper
I0731 03:41:30.084434  4416 detector.cpp:138] Detected a new leader: (id='7')
I0731 03:41:30.084646  4416 group.cpp:656] Trying to get '/mesos/info_0000000007' in ZooKeeper
W0731 03:41:30.086068  4416 detector.cpp:444] Leading master master@192.168.111.54:5050 is using a Protobuf binary format when registering with ZooKeeper (info): this 
will be deprecated as of Mesos 0.24 (see MESOS-2340)
I0731 03:41:30.086189  4416 detector.cpp:481] A new leading master (UPID=master@192.168.111.54:5050) is detected
I0731 03:41:30.086386  4416 sched.cpp:254] New master detected at master@192.168.111.54:5050
I0731 03:41:30.086664  4416 sched.cpp:264] No credentials provided. Attempting to register without authentication
I0731 03:41:30.089625  4416 sched.cpp:819] Got error 'Completed framework attempted to re-register'
I0731 03:41:30.089661  4416 sched.cpp:1625] Asked to abort the driver
03:41:30.090 [Thread-2] ERROR o.a.m.hdfs.scheduler.HdfsScheduler - Scheduler driver error: Completed framework attempted to re-register
I0731 03:41:30.090775  4416 sched.cpp:861] Aborting framework '20150730-154344-913287360-5050-25207-0001'
03:41:30.118 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.2.z-SNAPSHOT
03:41:30.155 [main] INFO  o.e.jetty.server.ServerConnector - Started ServerConnector@37918c79{HTTP/1.1}{0.0.0.0:8765}
03:41:30.155 [main] INFO  org.eclipse.jetty.server.Server - Started @962ms
```
